### ISSUE TITLE
discrete action scenarios

### ISSUE THREAD

**Issue by sgKevin1** [ChangyWen/wolpertinger_ddpg#3] opened 2021-07-19 01:18 UTC
Can this code handle discrete action scenarios?

**Comment by sgKevin1** [comment] 2021-07-19 03:19
I use gym's cartpole which has two actions, but the error happened. 
in main.py line 19, action = agent.random_action() will output the 'action = 2'
which will lead the file cartpole.py line 55 assert self.action_space.contains(action), "%r (%s) invalid"%(action, type(action)) happened error
![image](https://user-images.githubusercontent.com/51041913/126097553-7b010603-bdc8-4615-929c-09ebeadde16d.png)
I check the code and think the question maybe happen in file wolp_agent.py line 7 the function random_action()
could you please tell me why the problem happen and what's the mean of raw_action and action in function random_action()?, and why random_action output the action?

**Comment by sgKevin1** [comment] 2021-07-19 09:38
I met another question
In the file train_test.py line 56  agent.memory.append(
                    s_t,
                    agent.select_action(s_t),
                    0., True
                )
why reward is 0?

**Comment by ChangyWen** [comment] 2021-09-06 09:30
Sorry for the late reply.
Would you please provide more info of your settings (e.g., gym env and other parameters in args)? I would like to reproduce your results so that I can look into the it further. Thank you.

**Comment by ChangyWen** [comment] 2021-09-06 09:59
> I met another question
> In the file train_test.py line 56 agent.memory.append(
> s_t,
> agent.select_action(s_t),
> 0., True
> )
> why reward is 0?

The reward of an action that triggers the end of the end of an episode is usually set as 0.

**Comment by ChangyWen** [comment] 2021-09-06 10:32
> I use gym's cartpole which has two actions, but the error happened.
> in main.py line 19, action = agent.random_action() will output the 'action = 2'
> which will lead the file cartpole.py line 55 assert self.action_space.contains(action), "%r (%s) invalid"%(action, type(action)) happened error
> ![image](https://user-images.githubusercontent.com/51041913/126097553-7b010603-bdc8-4615-929c-09ebeadde16d.png)
> I check the code and think the question maybe happen in file wolp_agent.py line 7 the function random_action()
> could you please tell me why the problem happen and what's the mean of raw_action and action in function random_action()?, and why random_action output the action?

I have located the bug. The error is because that the input action index is out of range. Taking the 'CartPole-v1' env as an example. Its size of (discrete) action space is 2 (either moving to left or to right). The input action index for 'env.step(indexOfAction)' should be 0 or 1. But in my code, the input action is indexed by 1 and 2. 
I will fix it later. 
(Please note that I am really busy these days, and I will fix it ASAP.)

**Comment by ChangyWen** [comment] 2021-09-06 10:33
> Can this code handle discrete action scenarios?

The code is supposed to compatible with the gym environments with discrete action space. But as you have found a bug in these cases, I will fix it later. 
Thank you!

**Comment by ChangyWen** [comment] 2021-09-06 14:43
I have just updated the repo. It should be bug-free for both continuous and discrete gym environments now.
Thank you!

**Closed as completed** 2021-09-06 14:43 UTC
